language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - find ./unicorecmsffl -name '*.py' | xargs pep8
  - find ./unicorecmsffl -name '*.py' | xargs pyflakes
  - ./run_tests.sh
after_success:
  - coveralls
